/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as GameRouteImport } from './routes/game'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewGameScenarioRouteImport } from './routes/new-game/scenario'
import { Route as NewGameCrewRouteImport } from './routes/new-game/crew'
import { Route as GameMapRouteImport } from './routes/game/map'

const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGameScenarioRoute = NewGameScenarioRouteImport.update({
  id: '/new-game/scenario',
  path: '/new-game/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGameCrewRoute = NewGameCrewRouteImport.update({
  id: '/new-game/crew',
  path: '/new-game/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMapRoute = GameMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/game': typeof GameRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/game/map': typeof GameMapRoute
  '/new-game/crew': typeof NewGameCrewRoute
  '/new-game/scenario': typeof NewGameScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/game': typeof GameRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/game/map': typeof GameMapRoute
  '/new-game/crew': typeof NewGameCrewRoute
  '/new-game/scenario': typeof NewGameScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/game': typeof GameRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/game/map': typeof GameMapRoute
  '/new-game/crew': typeof NewGameCrewRoute
  '/new-game/scenario': typeof NewGameScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/game'
    | '/preferences'
    | '/game/map'
    | '/new-game/crew'
    | '/new-game/scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/game'
    | '/preferences'
    | '/game/map'
    | '/new-game/crew'
    | '/new-game/scenario'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/game'
    | '/preferences'
    | '/game/map'
    | '/new-game/crew'
    | '/new-game/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  GameRoute: typeof GameRouteWithChildren
  PreferencesRoute: typeof PreferencesRoute
  NewGameCrewRoute: typeof NewGameCrewRoute
  NewGameScenarioRoute: typeof NewGameScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-game/scenario': {
      id: '/new-game/scenario'
      path: '/new-game/scenario'
      fullPath: '/new-game/scenario'
      preLoaderRoute: typeof NewGameScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-game/crew': {
      id: '/new-game/crew'
      path: '/new-game/crew'
      fullPath: '/new-game/crew'
      preLoaderRoute: typeof NewGameCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/map': {
      id: '/game/map'
      path: '/map'
      fullPath: '/game/map'
      preLoaderRoute: typeof GameMapRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameMapRoute: typeof GameMapRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameMapRoute: GameMapRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  GameRoute: GameRouteWithChildren,
  PreferencesRoute: PreferencesRoute,
  NewGameCrewRoute: NewGameCrewRoute,
  NewGameScenarioRoute: NewGameScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
